name: Build

on:

  push:
    branches: [ main ]

  pull_request:

  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # allow the workflow to be re-used in other workflows
  workflow_call:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          # cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      # - name: Lint
        # run: npm run lint
