name: Deploy (SSH)

on:
  push:
    branches: [ main ]

  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    uses: ./.github/workflows/build.yml

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        env:
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
        with:
          timeout: 1m
          debug: true
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: PROJECT_PATH
          script: |
            whoami
            cd $PROJECT_PATH
            git pull
            npm i
            npm run build
